# Generated by Django 4.0.4 on 2022-05-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_division_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('function', models.CharField(max_length=500)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.division')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
