# Generated by Django 4.0.4 on 2022-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_historicalitem_image_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='broken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='broken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
