# Generated by Django 4.0.4 on 2022-06-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_historicalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Second', 'Second'), ('Bad', 'Bad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Second', 'Second'), ('Bad', 'Bad')], max_length=100),
        ),
    ]
