# Generated by Django 4.0.6 on 2022-07-16 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0003_historicalitem_borrowed_historicalitem_broken_and_more'),
        ('user', '0008_alter_division_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('requestee_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestee_division', to='user.division')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor', to='user.account')),
                ('requestor_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor_division', to='user.division')),
            ],
        ),
    ]
