# Generated by Django 4.0.4 on 2022-05-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_division_leader'),
        ('task', '0004_alter_task_requestee_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requestor',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='requestee_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.division'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requestor_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='user.division'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Shipping', 'Shipping'), ('Finished', 'Finished')], max_length=20),
        ),
    ]
