# Generated by Django 4.0.4 on 2022-05-30 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_requestee_remove_task_requestor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-date_added', '-id')},
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
