# Generated by Django 4.0.4 on 2022-07-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_options_alter_task_date_added'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['requestee_division', 'requestor_division'], name='task_task_request_f4f074_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'status', 'date_added'], name='task_task_priorit_3a2e11_idx'),
        ),
    ]
