# Generated by Django 4.0.4 on 2022-05-18 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_of', to='user.account'),
        ),
    ]
