# Generated by Django 4.0.4 on 2022-05-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_division_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_of', to='user.account'),
        ),
    ]
