# Generated by Django 4.0.4 on 2022-05-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_division_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name',)},
        ),
    ]
